return
{
    animation = require(... .. ".animation"),
    async = require(... .. ".async"),
    dbus_proxy = require(... .. ".dbus_proxy"),
    file = require(... .. ".filesystem.file"),
    filesystem = require(... .. ".filesystem.filesystem"),
    stream = require(... .. ".filesystem.stream"),
    bezier = require(... .. ".bezier"),
    client = require(... .. ".client"),
    color = require(... .. ".color"),
    -- global_menu = require(... .. ".global_menu"),
    ical = require(... .. ".ical"),
    icon_theme = require(... .. ".icon_theme"),
    inotify = require(... .. ".inotify"),
    input = require(... .. ".input"),
    inspect = require(... .. ".inspect"),
    json = require(... .. ".json"),
    layout = require(... .. ".layout"),
    misc = require(... .. ".misc"),
    run = require(... .. ".run"),
    settings = require(... .. ".settings"),
    string = require(... .. ".string"),
    table = require(... .. ".table"),
    ui = require(... .. ".ui")
}