-------------------------------------------
-- @author https://github.com/Kasper24
-- @copyright 2021-2022 Kasper24
-------------------------------------------
return {
    animated_panel = require(... .. ".animated_panel"),
    animated_popup = require(... .. ".animated_popup"),
    arcchart = require(... .. ".arcchart"),
    button = require(... .. ".button"),
    background = require(... .. ".background"),
    battery_icon = require(... .. ".battery_icon"),
    calendar = require(... .. ".calendar"),
    checkbox = require(... .. ".checkbox"),
    client_font_icon  = require(... .. ".client_font_icon"),
    client_menu = require(... .. ".client_menu"),
    client_thumbnail = require(... .. ".client_thumbnail"),
    dropdown = require(... .. ".dropdown"),
    graph = require(... .. ".graph"),
    menu = require(... .. ".menu"),
    overflow = require(... .. ".overflow"),
    playerctl = require(... .. ".playerctl"),
    piechart = require(... .. ".piechart"),
    popup = require(... .. ".popup"),
    profile = require(... .. ".profile"),
    progressbar = require(... .. ".progressbar"),
    prompt = require(... .. ".prompt"),
    rofi_grid = require(... .. ".rofi_grid"),
    screen_mask = require(... .. ".screen_mask"),
    scrollbar = require(... .. ".scrollbar"),
    slider_prompt = require(... .. ".slider_prompt"),
    slider = require(... .. ".slider"),
    spinning_circle = require(... .. ".spinning_circle"),
    text = require(... .. ".text"),
    textclock = require(... .. ".textclock"),
    titlebar = require(... .. ".titlebar"),
}
